plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.okazakee.pearlift'
version = '0.0.1'

android {
  namespace "expo.modules.pearliftresttimer"
  defaultConfig {
    // Required by Expo autolinking/publication tooling.
    versionCode 1
    versionName "0.0.1"
  }
}
